### ISSUE TITLE
Tagged versions past v0.3.0 not in General Registry

### ISSUE THREAD

**Issue by DanBerge** [peterkovesi/PerceptualColourMaps.jl#20]
Versions past v0.3.0 are not in the General Registry.

https://github.com/JuliaRegistries/General/blob/master/P/PerceptualColourMaps/Versions.toml

**Comment by peterkovesi** [comment]
Sorry , in my ignorance over the last year or so I had been making releases but not registering them!
We are up to 0.3.3  . Ideally I should register 0.3.1 and 0.3.2 so that Registrator can merge them automatically in sequence.  However, 0.3.1 never had a Project.toml file and 0.3.2 compat did not have proper upper bounds on some packages.  0.3.3 will therefore need to be merged into the registry manually by the long suffering people who manage that.  Hopefully I will have this mess sorted out in a day or so.
