### ISSUE TITLE
lightness peak in C10

### ISSUE THREAD

**Issue by hofmannmartin** [peterkovesi/PerceptualColourMaps.jl#28]
I was searching for a isoluminant cyclic color map, which is why I came across your awesome collection of color maps. 

From the documentation, I understood that `C10` should do the trick. However, I found a lightness peak in the cyans.

```julia
using Colors, PerceptualColourMaps
cp = cmap("C10")
extrema(map(c-> Lab(c).l,cp))
```

yields `(67.0,67.3978)`, where I would expect the minimum and maximum value to be practical identical for an isoluminant color map. Is it possible to fix this?

**Comment by peterkovesi** [comment]
Thanks for finding this.

It seems the problem is being caused by the red values going out of gamut and being clipped when converting the Lab values in the colour map control point specification to RGB.
You can see this if you run

```
c10 = cmap("C10", diagnostics = true)
```
If one edits the chrominance value from `40 to 37 on line 1228 in cmap.jl`  the clipping is avoided and the lightness values are all 67 as desired.

This makes me a bit nervous as my MATLAB implementation does not go out of gamut when the chrominance value is 40.  This suggests that I have some issues in the Lab -> RGB and RGB -> Lab conversions in my code that I have to track down.

Rather than edit the code a workaround is to use the `chromaK` keyword parameter in `cmap()` to reduce the chrominance of the colour map values and keep things in gamut. A value of 0.98 seems to be enough to make things work (I was expecting to need a value 37/40 = 0.925   so something is definitely astray!)

```
c10 = cmap("C10", chromaK = 0.98, diagnostics = true)
```

Over the next few days I will have a look over the code to see what is going on to get a proper solution

Cheers
Peter

**Comment by hofmannmartin** [comment]
Thank you for the quick reply.

I have one follow up question. I was expecting the colors to have the same gray value, however I observe a quite significant band in the cyans. 
```julia
using Plots, Colors, PerceptualColourMaps

c10 = cmap("C10", chromaK = 0.98)
plot(map(c-> Gray(c).val,c10))
```
Or is my understanding of isoluminant off?

**Comment by peterkovesi** [comment]
The grey value is computed as a weighted sum of RGB values. Corresponds to Y in the YIQ representation used for TV transmission
```
Y = 0.299 R + 0.587 G + 0.114 B
```
Lightness in Lab is a non-linear function of the Y value from the CIE XYZ representation of a colour. It also depends on the illuminant one chooses to use, typically D65 or D50,  see <https://en.wikipedia.org/wiki/CIELAB_color_space>

One also has 'Intensity' from the HSI space which is the average of the RGB values and then 'Value' from the HSV representation.  So we have multiple values one can compute that all attempt to capture roughly the same quantity.

There are all sorts of effects that are hard to model, for example a highly saturated colour tends to be perceived lighter/brighter than the numbers would suggest.  The CIECAM02 colour appearance model is the latest attempt to capture these sorts of things. Ultimately I should get my code to use this though I expect the effect will be minimal for the purpose of constructing colour maps.

Out of curiosity may I ask what is your intended use of these constant lightness maps?   I generally find them not that useful unless I combine them with relief shading.

**Comment by hofmannmartin** [comment]
Thank you. I now understand why `C10` has varying gray values.

Sure, we aim to color complex data, where both `angle` and `abs` are important information. To this end I thought it would be great to start with a perceptionally uniform cyclic color map to encode angles and linearly scale down the colors with the absolute value of a complex number until they are black at `z=0+0im`. Hence, wanting to have equal gray values across the colormap.

Does such a color map exists?

**Comment by peterkovesi** [comment]
Yes, so often when one wants to encode orientation one also wants to encode amplitude.  It's hard! In effect one wants a 2D colour map, one axis for orientation and the other for amplitude.  Desaturating the colour towards black as you are intending is one option, you may also find desaturating towards white useful too. See <https://colorcet.com/userguide/index.html#cyclic> where I have done this for a scalogram.

**Comment by hofmannmartin** [comment]
Thank you. I now understand why `C10` has varying gray values.

Sure, we aim to color complex data, where both `angle` and `abs` are important information. To this end I thought it would be great to start with a perceptionally uniform cyclic color map to encode angles and linearly scale down the colors with the absolute value of a complex number until they are black at `z=0+0im`. Hence, wanting to have equal gray values across the colormap.

Does such a color map exists?

**Comment by peterkovesi** [comment]
Sorry for the slow response but I have finally registered a new release that fixes a number of long standing bugs in my code. The main problem with C10 was that its path had been specified with a linear spline  rather than order 3.  So rather than being a roughly circular path it was a square!  I also had a bug that affected the equalisation of isoluminant maps plus a smoothing error.  Sorry about all that!  If you install the latest version 0.3.5 you should have some better quality colour maps.  Get back to me if you encounter any more problems.  Thank you once again for raising this issue, several bugs have been fixed and the code is now much better as a result
